# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Nick Verhelle"
description:	       "A website and blog on penetration testing, hacking, and the cybersecurity industry. Explore posts, presentations, and resources and please reach out to connect!"
author:              "Nick Verhelle"
topic: penet

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
feed:
  path: rss-feed.xml
